### ISSUE TITLE
is sccb ok variable used?

### ISSUE THREAD

**Issue by ingbeeedd** [lllbbbyyy/FPGA-OV2640#2]
I don't think sccb ok is applied in reg intit?

**Comment by lllbbbyyy** [comment]
> I don't think sccb ok is applied in reg intit?

why do you think so?

**Comment by ingbeeedd** [comment]
I was wrong. I'm sorry. That's so where did you refer to the i2c register setting value?

**Comment by lllbbbyyy** [comment]
> I was wrong. I'm sorry. That's so where did you refer to the i2c register setting value?

At the beginning, our course teacher went to communicate with the camera manufacturer and obtained a reference document for register configuration. Then a few of our classmates tried different parameters and finally got the available register configuration

**Comment by ingbeeedd** [comment]
Thank you for your detailed apply
